### ISSUE TITLE
AutoInv - InventoryFull

### ISSUE THREAD

**Issue by SuperDude36** [CrazedMiner/PocketMine-MP-Plugins#13]
Can you make it so the auto inventory plugin sends a message when your inventory if full?

**Comment by eqMFqfFd** [comment]
@SuperDude36 
```php
if($event->getPlayer()->getInventory()->firstEmpty() === -1) {
// Do anything
 }
```

> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by JackNoordhuis** [comment]
This is a planned feature however, the plugin is no longer updated on this repo. You can view the development of the current version over [here](https://github.com/JackNoordhuis/AutoInv) or grab a copy of the latest development build from [poggit](https://poggit.pmmp.io/ci/JackNoordhuis/AutoInv/AutoInv).
