### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by NML32** [CrazedMiner/PocketMine-MP-Plugins#3]
A couple of user's have reported they can't run /stats command.

The console shows:
01:23:16 [CRITICAL] Unhandled exception executing command 'stats' in stats: Division by zero
01:23:16 [WARNING] RuntimeException: "Division by zero" (E_WARNING) in "/PvP-Stats_v1.2.phar/src/CrazedMiner/StatsCommand" at line 45

EDIT: I think if the player has 0 in either deaths or kills it fails.  At least the user I tested with had 0 deaths and got the above error until I gave her one death so kills and deaths had a value greater than 0.

Thanks,
Twitter: NML_Staff

**Comment by JackNoordhuis** [comment]
Fixed in v1.3 :)
