### ISSUE TITLE
[Suggestion] Add a command

### ISSUE THREAD

**Issue by EnderKenji** [CrazedMiner/PocketMine-MP-Plugins#5]
Add a command to disable fly(if op use this for a person, they will not able to use fly anymore until op do /fly enable) - /fly [ enable | disable ]

**Comment by JackNoordhuis** [comment]
/fly toggles fly on/off, it's also disabled whenever a user takes damage. There is no need to add a separate command when there is one that is already there.

**Comment by EnderKenji** [comment]
No I mean, 

/fly on/off = Can let those who hv perm can fly

/fly disable/enable = Op off the fly command , then the person who hv perm to use /fly on/off can't use the command until op enable the fly command.... ._.

U close it so fast man...
